# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

# Warnings currently triggered by your code
- ignore: {name: "Use camelCase"}
- ignore: {name: "Reduce duplication"}


# Specify additional command line arguments
#
# - arguments: [--color, --cpp-simple, -XQuasiQuotes]


# Turn on hints that are off by default
#
# Ban "module X(module X) where", to require a real export list
# - warn: {name: Use explicit module export list}
#
# Replace a $ b $ c with a . b $ c
# - group: {name: dollar, enabled: true}
#
# Generalise map to fmap, ++ to <>
# - group: {name: generalise, enabled: true}
